version: 2
jobs:
  terraform:
    docker:
      - image: "alpine:3.14.1"
    steps:
    - checkout
    - run:
        name: Terraform Install
        command: |
          wget https://releases.hashicorp.com/terraform/0.15.1/terraform_0.15.1_linux_amd64.zip
          unzip terraform_0.15.1_linux_amd64.zip -d /bin
          echo $TT

workflows:
  version: 2
  buil&push-dev:
    jobs:
      - terraform
