version: 2.1
parameters:
  application:
    type: boolean
    default: false
  bastion:
    type: boolean
    default: false
  database:
    type: boolean
    default: false
  main:
    type: boolean
    default: false
  network:
    type: boolean
    default: false
  secrets:
    type: boolean
    default: false
jobs:
  terraform-init:
    docker:
      - image: "alpine:3.14.1"
    parameters:
      project_path:
        type: string
    steps:
    - checkout
    - run:
        name: Terraform Install
        command: |
          wget https://releases.hashicorp.com/terraform/0.15.1/terraform_0.15.1_linux_amd64.zip
          unzip terraform_0.15.1_linux_amd64.zip -d /bin
    - run:
        name: Terraform Init
        command: |
          cd << parameters.project_path >>
          for i in $(echo $ACCOUNTS | sed "s/,/ /g")
          do
              echo "$i"
              ls
          done
          mkdir -p /tmp/core_dumps
          touch /tmp/core_dumps/test
    - store_artifacts:
        path: /tmp/core_dumps
        destination: terraform-state
  terraform-apply:
    docker:
      - image: "alpine:3.14.1"
    parameters:
      project_path:
        type: string
    steps:
    - checkout
    - run:
        name: Terraform Install
        command: |
          wget https://releases.hashicorp.com/terraform/0.15.1/terraform_0.15.1_linux_amd64.zip
          unzip terraform_0.15.1_linux_amd64.zip -d /bin
    - run:
        name: Terraform Apply
        command: |
          cd << parameters.project_path >>
          ls /tmp
          for i in $(echo $ACCOUNTS | sed "s/,/ /g")
          do
              echo "$i"
              ls
          done
workflows:
  application:
    jobs:
      - terraform-init:
          name: terrorm-init-application
          project_path: chaoskube
      - terraform-apply:
          name: terrorm-init-main
          project_path: chaoskube
          requires:
            - terrorm-init-application
