version: 2.1
parameters:
  application:
    type: boolean
    default: false
  bastion:
    type: boolean
    default: false
  database:
    type: boolean
    default: false
  main:
    type: boolean
    default: false
  network:
    type: boolean
    default: false
  secrets:
    type: boolean
    default: false
jobs:
  terraform-release:
    docker:
      - image: "alpine:3.14.1"
    parameters:
      project_path:
        type: string
    steps:
    - checkout
    - run:
        name: Terraform Install
        command: |
          apk add jq
          wget https://releases.hashicorp.com/terraform/0.15.1/terraform_0.15.1_linux_amd64.zip
          unzip terraform_0.15.1_linux_amd64.zip -d /bin
    - run:
        name: Terraform Init - Apply
        shell: /bin/sh
        command: |
          echo hello
          hello || true

workflows:
  application:
    jobs:
      - terraform-release:
          name: terrorm-network
          project_path: network
