version: 2.1
parameters:
  application:
    type: boolean
    default: false
  bastion:
    type: boolean
    default: false
  database:
    type: boolean
    default: false
  main:
    type: boolean
    default: false
  network:
    type: boolean
    default: false
  secrets:
    type: boolean
    default: false
jobs:
  terraform-release:
    docker:
      - image: "alpine:3.14.1"
    parameters:
      project_path:
        type: string
    steps:
    - checkout
    - run:
        name: Terraform Install
        command: |
          apk add jq
          wget https://releases.hashicorp.com/terraform/0.15.1/terraform_0.15.1_linux_amd64.zip
          unzip terraform_0.15.1_linux_amd64.zip -d /bin
    - run:
        name: Terraform Init
        command: |
          cd << parameters.project_path >>
          echo $ACCOUNTS | jq -r 'keys[]' | while read i; do
              WORKSPACE=$i
              ACCOUNT=$(echo $ACCOUNTS | jq -r ".$i.accountId")
              echo "The workspace is $WORKSPACE"
              echo "The account id is $ACCOUNT"
          done
          mkdir -p .terraform/
          touch .terraform/test-<< parameters.project_path >>
    - run:
        name: Terraform Init
        command: |
          ls
          pwd
workflows:
  application:
    jobs:
      - terraform-release:
          name: terrorm-init-application
          project_path: chaoskube
      - terraform-release:
          name: terrorm-init-main
          project_path: chaoskube
          requires:
            - terrorm-init-application
