version: 2
jobs:
  dockerbuild:
    docker:
      - image: "node:12.2.0-alpine"
    steps:
    - checkout
    - run:
        name: test
        command: |
        DIR=$(git diff-tree --no-commit-id --name-only -r HEAD)
        echo $DIR

workflows:
  version: 2
  buil&push-dev:
    jobs:
      - dockerbuild
